swagger: "2.0"
info:
  description: API documentation
  version: "0.1"
  title: The good tube
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

# Paths supported by the server application
paths:
  /config:
    get:
      operationId: "config.get_config"
      tags:
        - "Configuration"
      summary: "Get configuration"
      description: "Get configuration"
      responses:
        200:
          description: "Successful read configuration"
          schema:
            type: "object"
    put:
      operationId: "config.update_config"
      tags:
        - "Configuration"
      summary: "Update configuration"
      description: "Update configuration"
      parameters:
        - in: "body"
          name: "config"
          description: "Configuration parameters to update"
          schema:
            type: "object"
      responses:
        200:
          description: "Configuration updated"
  /version:
    get:
      operationId: "youtube-dl.version.version"
      tags:
        - "Information"
      summary: "Version of API and youtube-dl"
      description: "Get the version of this API and the youtube-dl embeded component"
      responses:
        200:
          description: "Successful read version operation"
          schema:
            type: "object"
            properties:
              api:
                type: "string"
              youtube-dl:
                type: "string"
  /supported_sites:
    get:
      operationId: "youtube-dl.supported_sites.supported_sites"
      tags:
        - "Information"
      summary: "List of supported sites"
      description: "Get the list of supported sites for extraction"
      responses:
        200:
          description: "Successful read list of supported sites"
          schema:
            type: "array"
            items:
              type: "string"
  /video_information:
    get:
      operationId: "youtube-dl.video_information.video_information"
      tags:
        - "Information"
      summary: "Video information"
      description: "List all information about a video (incl. available formats)"
      parameters:
        - in: "query"
          name: "url"
          required: true
          type: "string"
          description: "URL of the video you request information"
      responses:
        200:
          description: "Successful retrieve video information"
          schema:
            type: "object"
  /video_download:
    post:
      operationId: "youtube-dl.video_download.download"
      tags:
        - "Downloads"
      summary: "Video download"
      description: "Download a video in desired format from any available site"
      parameters:
        - in: "body"
          name: "data"
          description: "Download parameters"
          schema:
            type: "object"
            required:
              - url
            properties:
              url:
                type: "string"
      responses:
        201:
          description: "Download started"
  /downloads:
    get:
      operationId: "youtube-dl.downloads.list"
      tags:
        - "Downloads"
      summary: "List of downloads"
      description: "List of current downloads"
      responses:
        200:
          description: "Successful read list of downloads"
          schema:
            type: "array"
            items:
              type: "object"
  /downloads/stop:
    put:
      operationId: "youtube-dl.downloads.stop"
      tags:
        - "Downloads"
      summary: "Stop a download"
      description: "Stop a download from URL"
      parameters:
        - in: "query"
          name: "url"
          description: "Download URL"
          type: "string"
          required: true
      responses:
        200:
          description: "Successful stop download"
  /downloads/delete:
    delete:
      operationId: "youtube-dl.downloads.delete"
      tags:
        - "Downloads"
      summary: "Delete a download"
      description: "Delete a download from URL regardless its status. This also delete all related files."
      parameters:
        - in: "query"
          name: "url"
          description: "Download URL"
          type: "string"
          required: true
      responses:
        200:
          description: "Successful delete download"
  /downloads/clear:
    delete:
      operationId: "youtube-dl.downloads.clear"
      tags:
        - "Downloads"
      summary: "Clear a download"
      description: "Clear a finished download from URL."
      parameters:
        - in: "query"
          name: "url"
          description: "Download URL"
          type: "string"
          required: true
      responses:
        200:
          description: "Successful clear download"
  /downloads/clear_all:
    delete:
      operationId: "youtube-dl.downloads.clear_all"
      tags:
        - "Downloads"
      summary: "Clear all downloads"
      description: "Clear all finished downloads."
      responses:
        200:
          description: "Successful clear downloads"
